### ISSUE TITLE
The most recent version of Seaside no longer uses/supports GRPackge class 

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/Grease#32]
The Grease test `GRPackageTest >> #testPackages` has started failing in internal tests and it seems that the Seaside extensions expected by that test are no longer provided by the most recent version of [Seaside](https://github.com/SeasideSt/Seaside/commit/15231812d5e0614b6a0d74a077461aa9da75f792).

GRPackageTest >> #testPackages is the only test failure that we've seen ... and it fails when loaded against extent0.seaside.dbf (for GemStone 3.7.1.3) in internal tests ... 

[GsDevKit_stones/smalltalkCI tests are running fine](https://github.com/GsDevKit/Grease/actions/runs/10357290032), so the changes that I make will likely only affect the internal tests ...

**Comment by jbrichau** [comment]
I think this should be fixed now...
